version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10

anchors:
  deployment-branch-condition: &deployment-branch-condition
    filters:
      branches:
        only: main

jobs:
  prepare:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - pip-cache-{{ checksum "pyproject.toml" }}
            - pip-cache-
      - run:
          name: Create virtualenv and install deps
          command: |
            python -m venv .venv
            . .venv/bin/activate
            python -m pip install --upgrade pip
            pip install -e .[dev]
      - save_cache:
          paths:
            - ~/.cache/pip
          key: pip-cache-{{ checksum "pyproject.toml" }}
      - persist_to_workspace:
          root: .
          paths:
            - .venv
            - pyproject.toml
            - poetry.lock

  test:
    executor: python-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Activate venv and run tests
          command: |
            . .venv/bin/activate
            pytest -q

  lint:
    executor: python-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Activate venv and run lint
          command: |
            . .venv/bin/activate
            black --check src tests
            flake8 src tests

workflows:
  version: 2
  verification:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
          <<: *deployment-branch-condition
      - lint:
          requires:
            - test
          <<: *deployment-branch-condition
