version: 2.1

# This file is the "setup" phase only. It starts the agent work,
# prepares & persists workspace, and then continues with continue_config.yml

setup: true

orbs:
  continuation: circleci/continuation@2.0.1 #https://circleci.com/developer/orbs/orb/circleci/continuation
  path-filtering: circleci/path-filtering@2.0.4 #https://circleci.com/developer/orbs/orb/circleci/path-filtering

jobs:
  prepare:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - poetry-cache-{{ checksum "poetry.lock" }}
            # - poetry-cache-
      - run:
          name: Install Poetry (user-local)
          command: |
            python -m pip install --upgrade pip
            python -m pip install poetry
      - run:
          name: Cache poetry metadata (no install yet)
          command: |
            poetry --version
      - save_cache:
          paths:
            - ~/.cache/pypoetry
            - ~/.cache/pip
          key: poetry-cache-{{ checksum "poetry.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - pyproject.toml
            - poetry.lock

workflows:
  build-setup:
    jobs:
      - prepare
      - continuation/continue:
          requires:
            - prepare
          # path to the config you want to continue into
          configuration_path: .circleci/continue_config.yml
          # optional: parameters can be passed as a JSON string
          # parameters: '{ "some_flag": true }'
