version: 2.1

# Setup config — prepares workspace & continues to continue_config.yml
setup: true

orbs:
  continuation: circleci/continuation@2.0.1
  path-filtering: circleci/path-filtering@2.0.4

jobs:
  prepare:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - restore_cache:
          keys:
            - poetry-cache-v3-{{ checksum "poetry.lock" }}
            - poetry-cache-v3-

      - run:
          name: Install Poetry and dependencies
          command: |
            set -e
            python -m pip install --upgrade pip
            python -m pip install poetry
            poetry config virtualenvs.in-project true  # creates .venv in repo
            poetry install --no-interaction --no-ansi

      - save_cache:
          paths:
            - .venv
          key: poetry-cache-v3-{{ checksum "poetry.lock" }}

      - persist_to_workspace:
          root: .
          paths:
            - pyproject.toml
            - poetry.lock
            - .venv  # persist venv so next jobs don’t reinstall

workflows:
  build-setup:
    jobs:
      - prepare
      - continuation/continue:
          requires:
            - prepare
          configuration_path: .circleci/continue_config.yml
